// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMY52qlMNoTYxhhREMsT8xkpe2haOacCA',
    appId: '1:356823060418:android:56f21db161b8d71a4dd05b',
    messagingSenderId: '356823060418',
    projectId: 'fixauth-cca12',
    storageBucket: 'fixauth-cca12.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhnNqeK9pEFY0jd3-NLgz_JQFx-JQokzM',
    appId: '1:356823060418:ios:538ac0569563ecf54dd05b',
    messagingSenderId: '356823060418',
    projectId: 'fixauth-cca12',
    storageBucket: 'fixauth-cca12.appspot.com',
    androidClientId: '356823060418-5phia3p39bk7d93qpqctja15bmb7rrh3.apps.googleusercontent.com',
    iosClientId: '356823060418-5nhosgt4lnjk968na5pt1e4a6th06571.apps.googleusercontent.com',
    iosBundleId: 'com.example.fixDatesApp',
  );
}
