import 'package:flutter/material.dart';

List<Map<String, dynamic>> contactList = [
  {
    'title': 'Alice',
    'subtitle': null,
    'color': Colors.white,
    'time': '',
    'imagePath': 'https://example.com/path_to_image1.jpg',
  },
  {
    'title': 'Bob',
    'subtitle': null,
    'color': Colors.white,
    'time': '',
    'imagePath': 'https://example.com/path_to_image2.jpg',
  },
  {
    'title': 'Charlie',
    'subtitle': null,
    'color': Colors.white,
    'time': '',
    'imagePath': 'https://example.com/path_to_image3.jpg',
  },
  {
    'title': 'David',
    'subtitle': null,
    'color': Colors.white,
    'time': '',
    'imagePath': 'https://example.com/path_to_image4.jpg',
  },
  {
    'title': 'Emily',
    'subtitle': null,
    'color': Colors.white,
    'time': '',
    'imagePath': 'https://example.com/path_to_image5.jpg',
  },
  {
    'title': 'Frank',
    'subtitle': null,
    'color': Colors.white,
    'time': '',
    'imagePath': 'https://example.com/path_to_image6.jpg',
  },
  {
    'title': 'Grace',
    'subtitle': null,
    'color': Colors.white,
    'time': '',
    'imagePath': 'https://example.com/path_to_image7.jpg',
  },
  {
    'title': 'Henry',
    'subtitle': null,
    'color': Colors.white,
    'time': '',
    'imagePath': 'https://example.com/path_to_image8.jpg',
  },
  {
    'title': 'Ivy',
    'subtitle': null,
    'color': Colors.white,
    'time': '',
    'imagePath': 'https://example.com/path_to_image9.jpg',
  },
  {
    'title': 'Jack',
    'subtitle': null,
    'color': Colors.white,
    'time': '',
    'imagePath': 'https://example.com/path_to_image10.jpg',
  },
  {
    'title': 'Katie',
    'subtitle': null,
    'color': Colors.white,
    'time': '',
    'imagePath': 'https://example.com/path_to_image11.jpg',
  },
  {
    'title': 'Liam',
    'subtitle': null,
    'color': Colors.white,
    'time': '',
    'imagePath': 'https://example.com/path_to_image12.jpg',
  },
  {
    'title': 'Mia',
    'subtitle': null,
    'color': Colors.white,
    'time': '',
    'imagePath': 'https://example.com/path_to_image13.jpg',
  },
  {
    'title': 'Noah',
    'subtitle': null,
    'color': Colors.white,
    'time': '',
    'imagePath': 'https://example.com/path_to_image14.jpg',
  },
  {
    'title': 'Olivia',
    'subtitle': null,
    'color': Colors.white,
    'time': '',
    'imagePath': 'https://example.com/path_to_image15.jpg',
  },
  {
    'title': 'Piper',
    'subtitle': null,
    'color': Colors.white,
    'time': '',
    'imagePath': 'https://example.com/path_to_image16.jpg',
  },
  {
    'title': 'Quinn',
    'subtitle': null,
    'color': Colors.white,
    'time': '',
    'imagePath': 'https://example.com/path_to_image17.jpg',
  },
  {
    'title': 'Ryan',
    'subtitle': null,
    'color': Colors.white,
    'time': '',
    'imagePath': 'https://example.com/path_to_image18.jpg',
  },
  {
    'title': 'Sophia',
    'subtitle': null,
    'color': Colors.white,
    'time': '',
    'imagePath': 'https://example.com/path_to_image19.jpg',
  },
  {
    'title': 'Tyler',
    'subtitle': null,
    'color': Colors.white,
    'time': '',
    'imagePath': 'https://example.com/path_to_image20.jpg',
  },
];
