import 'package:flutter/material.dart';

List<Map<String, dynamic>> events = [
  {
    'title': 'Mobile Application',
    'subtitle': 'Event Created',
    'color': Colors.green,
    'time': '38m',
    'imagePath':
        'https://media.licdn.com/dms/image/D4E03AQEzsOR7x1_qKw/profile-displayphoto-shrink_800_800/0/1666714485434?e=2147483647&v=beta&t=FXjmwhiEwvBvlVdHr605HjnYQ79yY_tnsOMZWshBj_s',
  },
  {
    'title': 'Flutter Workshop',
    'subtitle': 'New Project Kick-off',
    'color': Colors.blue,
    'time': '1h',
    'imagePath': 'https://example.com/path_to_image2.jpg',
  },
  {
    'title': 'Networking Event',
    'subtitle': 'Meet and Greet',
    'color': Colors.orange,
    'time': '2h',
    'imagePath': 'https://example.com/path_to_image3.jpg',
  },
  {
    'title': 'UI/UX Design Seminar',
    'subtitle': 'Design Trends Discussion',
    'color': Colors.purple,
    'time': '1h 30m',
    'imagePath': 'https://example.com/path_to_image4.jpg',
  },
  {
    'title': 'Tech Conference',
    'subtitle': 'Keynote Speakers and Panels',
    'color': Colors.red,
    'time': '3h',
    'imagePath': 'https://example.com/path_to_image5.jpg',
  },
  {
    'title': 'Coding Bootcamp',
    'subtitle': 'Hands-on Coding Sessions',
    'color': Colors.teal,
    'time': '4h',
    'imagePath': 'https://example.com/path_to_image6.jpg',
  },
  {
    'title': 'Startup Pitch Day',
    'subtitle': 'Innovative Ideas Showcase',
    'color': Colors.amber,
    'time': '2h 30m',
    'imagePath': 'https://example.com/path_to_image7.jpg',
  },
  {
    'title': 'Hackathon',
    'subtitle': '24-hour Coding Challenge',
    'color': Colors.indigo,
    'time': 'Ongoing',
    'imagePath': 'https://example.com/path_to_image8.jpg',
  },
  {
    'title': 'Web Development Workshop',
    'subtitle': 'Latest Web Technologies',
    'color': Colors.deepOrange,
    'time': '1h 45m',
    'imagePath': 'https://example.com/path_to_image9.jpg',
  },
  {
    'title': 'AI and Machine Learning Symposium',
    'subtitle': 'Advancements in AI',
    'color': Colors.lightBlue,
    'time': '2h 15m',
    'imagePath': 'https://example.com/path_to_image10.jpg',
  },
  {
    'title': 'Data Science Meetup',
    'subtitle': 'Data Analysis Techniques',
    'color': Colors.brown,
    'time': '1h 30m',
    'imagePath': 'https://example.com/path_to_image11.jpg',
  },
  {
    'title': 'E-commerce Forum',
    'subtitle': 'Future of Online Retail',
    'color': Colors.cyan,
    'time': '2h 30m',
    'imagePath': 'https://example.com/path_to_image12.jpg',
  },
  {
    'title': 'Cybersecurity Conference',
    'subtitle': 'Security Threats and Solutions',
    'color': Colors.pink,
    'time': '3h',
    'imagePath': 'https://example.com/path_to_image13.jpg',
  },
  {
    'title': 'Mobile Game Development Workshop',
    'subtitle': 'Creating Engaging Games',
    'color': Colors.lime,
    'time': '1h 45m',
    'imagePath': 'https://example.com/path_to_image14.jpg',
  },
  {
    'title': 'Blockchain Summit',
    'subtitle': 'Decentralized Technologies',
    'color': Colors.deepPurple,
    'time': '2h 15m',
    'imagePath': 'https://example.com/path_to_image15.jpg',
  },
  {
    'title': 'Virtual Reality Showcase',
    'subtitle': 'Immersive Experiences',
    'color': Colors.grey,
    'time': '1h 30m',
    'imagePath': 'https://example.com/path_to_image16.jpg',
  },
  {
    'title': 'Digital Marketing Conference',
    'subtitle': 'Strategies and Trends',
    'color': Colors.yellow,
    'time': '2h 30m',
    'imagePath': 'https://example.com/path_to_image17.jpg',
  },
  {
    'title': 'Health Tech Symposium',
    'subtitle': 'Innovations in Healthcare',
    'color': Colors.blueGrey,
    'time': '3h',
    'imagePath': 'https://example.com/path_to_image18.jpg',
  },
  {
    'title': 'Design Thinking Workshop',
    'subtitle': 'Creative Problem Solving',
    'color': Colors.deepPurpleAccent,
    'time': '1h 45m',
    'imagePath': 'https://example.com/path_to_image19.jpg',
  },
  {
    'title': 'Robotics Expo',
    'subtitle': 'Cutting-edge Robotics',
    'color': Colors.lightGreen,
    'time': '2h 15m',
    'imagePath': 'https://example.com/path_to_image20.jpg',
  },
];
